fix(11936): done
rollun-com/service-compatible-vehicles pull request #13
Opened 2022-08-16 10:30 UTC by aKrulykovskyi

2022-08-17 16:16 UTC, rollun-com requested changes

2022-08-17 16:16 UTC, rollun-com commented on src/services/compatible-vehicles/update-compatible-vehicle-list.ts
> +  });
это .filter :)

2022-08-17 16:16 UTC, rollun-com commented on src/services/compatible-vehicles/update-compatible-vehicle-list.ts
> +
а если будет 1000 делитов, оно же умрёт просто, давай сделаем запросы в чанках по 10 хотяб

2022-08-17 16:16 UTC, rollun-com commented on src/services/compatible-vehicles/update-compatible-vehicle-list.ts
> +
плюс, ерор хэндлинг?

2022-08-18 10:04 UTC, artemka-debug approved these changes

2022-08-18 10:05 UTC, merged